### ISSUE TITLE
Suddenly closes without doing the work

### ISSUE THREAD

**Issue by lautig** [NickvisionApps/Tagger#146]

**Comment by fsobolev** [comment]
Please provide at least some info.
Try running the app in terminal and get the output when it crashes.
For flatpak:

```
flatpak run org.nickvision.tagger
```
For snap:

```
tagger
```

See [contributing guidelines](https://github.com/NickvisionApps/Tagger/blob/main/CONTRIBUTING.md#reporting-bugs) to understand what other info you can provide to help us fix the problem.

**Comment by nlogozzo** [comment]
> without doing the work

What was "the work" you were trying to do?

**Comment by lautig** [comment]
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/run/user/1000/doc/dc2395e5/VideoDownloader/Chapter I.mp3' is denied.
 ---> System.IO.IOException: Permiso denegado
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at TagLib.File.LocalFileAbstraction.get_WriteStream()
   at TagLib.File.set_Mode(AccessMode value)
   at TagLib.NonContainer.File.Save()
   at NickvisionTagger.Shared.Models.MusicFile.SaveTagToDisk(Boolean preserveModificationTimestamp) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 431
   at NickvisionTagger.Shared.Controllers.MainWindowController.<SaveSelectedTagsAsync>b__52_0() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 351
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at NickvisionTagger.Shared.Controllers.MainWindowController.SaveSelectedTagsAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 345
   at NickvisionTagger.GNOME.Views.MainWindow.Apply(SimpleAction sender, EventArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 500
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by nlogozzo** [comment]
Ah, please use Flatseal to grant Tagger filesystem access. Once you do that, open the same folder again in Tagger and it should work...

**Comment by nlogozzo** [comment]
> @lautig what distro do you use? It's second time this error is reported, but we can't reproduce it... So maybe it's something distro-specific.

I believe it's from old Tagger that has home permission to now new Tagger that doesnt and everyone just needs to reopen their folder to get portal permission because it's reading path from old Tagger config

**Comment by fsobolev** [comment]
> I believe it's from old Tagger that has home permission to now new Tagger that doesnt and everyone just needs to reopen their folder to get portal permission because it's reading path from old Tagger config

Tagger doesn't open anything if it can't access saved folder on start. And in logs the folders are clearly opened with portals (`/run/user...`). I don't want to go that far in assumptions, but to me it seems like a bug in specific version of flatpak or portals.

**Comment by nlogozzo** [comment]
> > I believe it's from old Tagger that has home permission to now new Tagger that doesnt and everyone just needs to reopen their folder to get portal permission because it's reading path from old Tagger config
> 
> Tagger doesn't open anything if it can't access saved folder on start. And in logs the folders are clearly opened with portals (`/run/user...`). I don't want to go that far in assumptions, but to me it seems like a bug in specific version of flatpak or portals.

Could be 🤷‍♂️...either way granting full filesystem access through Flatseal and then reopening the folder seems to be a for now

**Comment by lautig** [comment]
> @lautig what distro do you use? It's second time this error is reported, but we can't reproduce it... So maybe it's something distro-specific.

I am on Debian 12.

I realized I had same issue with app Ear Tag and also got solved by allowing access. 
Thank you all for the help!

**Comment by fsobolev** [comment]
> I am on Debian 12.
> I realized I had same issue with app Ear Tag and also got solved by allowing access.

I'm glad it helped, but breaking the sandbox is not a proper solution, it will be nice if you could report the problem on Debian issue tracker, you and other Debian users probably will have the same issue with other apps too.
