### ISSUE TITLE
SegmentationFault when loading library

### ISSUE THREAD

**Issue by dominikheinz** [NickvisionApps/Tagger#168]
**Summary:**

When opening the Music directory in Tagger, the application crashes. Checking `journalctl` gives me the following log:

```
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]: Unhandled exception. TagLib.CorruptFileException: Text delimiter expected.
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at TagLib.Id3v2.SynchronisedLyricsFrame.ParseFields(ByteVector data, Byte version)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at TagLib.Id3v2.FrameFactory.CreateFrame(ByteVector data, File file, Int32& offset, Byte version, Boolean alreadyUnsynched)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at TagLib.Id3v2.Tag.Parse(ByteVector data, File file, Int64 position, ReadStyle style)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at TagLib.Id3v2.Tag.Read(File file, Int64 position, ReadStyle style)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at TagLib.NonContainer.StartTag.ReadTag(Int64& start, ReadStyle style)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at TagLib.NonContainer.StartTag.Read(ReadStyle style)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at InvokeStub_AudioFile..ctor(Object, Object, IntPtr*)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle proper>
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.Shared.Models.MusicFile.LoadTagFromDisk() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 238
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.Shared.Models.MusicFile..ctor(String path) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 98
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.Shared.Models.MusicFolder.<>c__DisplayClass17_0.<ReloadMusicFilesAsync>b__0() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFolder.cs:line >
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]: --- End of stack trace from previous location ---
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]: --- End of stack trace from previous location ---
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.Shared.Models.MusicFolder.ReloadMusicFilesAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFolder.cs:line 52
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.Shared.Controllers.MainWindowController.ReloadFolderAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 225
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.Shared.Controllers.MainWindowController.OpenFolderAsync(String path) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:>
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.Shared.Controllers.MainWindowController.StartupAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 169
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.GNOME.Views.MainWindow.StartAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 326
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at NickvisionTagger.GNOME.Program.OnActivate(Application sedner, EventArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Program.cs:line 118
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Jul 25 14:52:04 workstation org.nickvision.tagger.desktop[6089]:    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Jul 25 14:52:04 workstation systemd[1]: Started Process Core Dump (PID 6186/UID 0).
Jul 25 14:52:06 workstation systemd-coredump[6187]: [🡕] Process 6089 (NickvisionTagge) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 42:
                                                    #0  0x00007fe327091184 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x91184)
                                                    #1  0x00007fe32703f00e n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x3f00e)
                                                    #2  0x00007fe3270287fc n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x287fc)
                                                    #3  0x00007fe326e4cff2 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x64cff2)
                                                    #4  0x00007fe326e4cf12 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x64cf12)
                                                    #5  0x00007fe326c10185 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x410185)
                                                    #6  0x00007fe326c10266 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x410266)
                                                    #7  0x00007fe326b61a29 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x361a29)
                                                    #8  0x00007fe2a9f8cdca n/a (n/a + 0x0)
                                                    #9  0x00007fe2a7b31e55 n/a (n/a + 0x0)
                                                    #10 0x00007fe2a7b28212 n/a (n/a + 0x0)
                                                    #11 0x00007fe326cc4a57 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x4c4a57)
                                                    #12 0x00007fe326af3a7e n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x2f3a7e)
                                                    #13 0x00007fe326b0bb82 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x30bb82)
                                                    #14 0x00007fe326abc39a n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x2bc39a)
                                                    #15 0x00007fe326abc99d n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x2bc99d)
                                                    #16 0x00007fe326b0bc57 n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x30bc57)
                                                    #17 0x00007fe326e51bbe n/a (/app/lib/org.nickvision.tagger/libcoreclr.so + 0x651bbe)
                                                    #18 0x00007fe32708f1da n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x8f1da)
                                                    #19 0x00007fe327117f44 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x117f44)
                                                    ELF object binary architecture: AMD x86-64
Jul 25 14:52:06 workstation systemd[1]: systemd-coredump@1-6186-0.service: Deactivated successfully.
```

there is also a bunch of assertion messages:

```
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
Jul 25 14:51:40 workstation NickvisionTagge[6089]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
```

**Comment by fsobolev** [comment]
Please try [latest beta](https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.1-beta3), Tagger uses ATL instead of Taglib now, it should handle files better.

**Comment by dominikheinz** [comment]
I can confirm it works perfectly fine with the beta version. Is there an ETA when this version will be out of beta?

**Comment by nlogozzo** [comment]
> I can confirm it works perfectly fine with the beta version. Is there an ETA when this version will be out of beta?

RC1 will be released tonight and stable by Friday (give time to translators to update translations)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.1-rc1

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/edit/2023.7.1
stable is here :)
