### ISSUE TITLE
Crash when submitting AccoustId

### ISSUE THREAD

**Issue by jrom99** [NickvisionApps/Tagger#211]
## Describe the bug

Tagger crashes when trying to upload data to AccoustId.

## Screenshot/Video
[Screencast from 2023-08-02 19-58-58.webm](https://github.com/NickvisionApps/Tagger/assets/47498278/c2e14e47-1671-4696-b17b-c49072489297)

## System information

Tagger version: 2023.8.0 (from flathub)
OS: Ubuntu 23.04
Session type: wayland

## Additional context

[tagger_debug.txt](https://github.com/NickvisionApps/Tagger/files/12245381/tagger_debug.txt)

Crash log:
```
(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.743: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.743: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.747: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.747: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.747: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.747: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.769: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.769: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.770: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.770: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.770: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.770: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.800: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.800: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.801: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.801: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.801: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.801: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.814: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.814: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.834: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.834: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.837: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.837: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.837: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.837: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.854: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.854: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.859: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.859: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.860: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.860: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.885: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.885: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.889: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.889: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.890: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.890: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.901: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.901: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.905: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.905: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.906: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.906: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.921: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.921: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.925: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.925: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.926: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.926: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.950: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.950: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.954: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.954: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.955: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:40.955: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:59.599: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:59.599: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:59.601: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:59.601: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:59.601: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:58:59.601: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.742: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.742: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.749: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.749: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.749: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.749: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.752: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.752: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.762: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.762: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.764: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.765: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.765: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.765: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.777: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.777: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.779: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.779: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.779: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.779: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.802: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.802: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.805: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.805: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.805: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.805: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.831: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.831: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.834: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.834: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.834: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.834: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.857: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.857: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.860: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.860: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.860: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.860: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.865: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.865: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.901: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.901: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.904: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.904: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.904: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.904: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.910: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.910: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.922: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.922: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.924: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.924: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.925: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.925: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.932: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.933: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.935: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.935: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.935: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.935: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.955: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.955: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.958: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.958: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.958: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(NickvisionTagger.GNOME:2): Gtk-CRITICAL **: 19:59:00.958: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
UnhandledException - unhandled exception: System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NickvisionTagger.Shared.Controllers.MainWindowController.SubmitToAcoustIdAsync(String recordingID) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 790
   at NickvisionTagger.GNOME.Views.MainWindow.<>c__DisplayClass79_0.<<SubmitToAcoustId>b__0>d.MoveNext() in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 768
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass3_0.<ScheduleAction>b__0()
```

**Comment by nlogozzo** [comment]
Please test this build: https://github.com/NickvisionApps/Tagger/actions/runs/5744687505

*Artifacts will appear as soon as the build is finished*

I thank you for finding all these little things ❤️

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.1
