### ISSUE TITLE
app crashes with too many lookups

### ISSUE THREAD

**Issue by legacychimera247** [NickvisionApps/Tagger#233]
tried to lookup on musicbrainz for an entire folder (meaning as an artist folder) and the app always crash

if useful this is the terminal output

`UnhandledException - unhandled exception: System.Xml.XmlException: There are multiple root elements. Line 2, position 2.
   at AcoustID.Web.LookupService.GetAsync(String fingerprint, Int32 duration, String[] meta)
   at NickvisionTagger.Shared.Models.MusicFile.LoadTagFromMusicBrainzAsync(String acoustIdClientKey, String version, Boolean overwriteTagWithMusicBrainz, Boolean overwriteAlbumArtWithMusicBrainz) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 300
   at NickvisionTagger.Shared.Controllers.MainWindowController.DownloadMusicBrainzMetadataAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 824
   at NickvisionTagger.GNOME.Views.MainWindow.DownloadMusicBrainzMetadata(SimpleAction sender, EventArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 734
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass3_0.<ScheduleAction>b__0()
[luca247@fedora ~]$ 

`

**Comment by nlogozzo** [comment]
Please try out the fix in this release: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.2-rc1
