### ISSUE TITLE
doing a drag'n'drop crashes the app

### ISSUE THREAD

**Issue by legacychimera247** [NickvisionApps/Tagger#259]
Hello there, i guess the title says it all

this is the terminal output...

`UnhandledException - unhandled exception: System.InvalidCastException: Unable to cast object of type 'GObject.Object' to type 'Gio.File'.
   at NickvisionTagger.GNOME.Views.MainWindow.OnDrop(DropTarget sender, DropSignalArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 563
   at GObject.ReturningSignal`3.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)`

by the way, thank you for developing beautiful gnome apps :)

**Comment by nlogozzo** [comment]
Are you running the flatpak version of the app?

**Comment by legacychimera247** [comment]
yes, flatpak one

**Comment by nlogozzo** [comment]
> yes, flatpak one

I am going to fix the issue of where the whole app crashes upon drag and drop, however it is a known flatpak issue that drag and drop doesn't fully work correctly, so expect it not to work, but at least it won't crash.

**Comment by nlogozzo** [comment]
Please try the beta and let me know how it goes: https://github.com/NickvisionApps/Tagger/releases/tag/2023.8.3-beta1 :)
