### ISSUE TITLE
tagger (beta) crashes when exiting lyrics screen

### ISSUE THREAD

**Issue by legacychimera247** [NickvisionApps/Tagger#287]
hello there, tried your beta for resolving the drag'n'drop issue, now a plus icon cursor is shown but nothing happens and app does not crash anymore, so it's solved i would say, until gnome implements proper drag'n'drop

anyway, i noticed that the app closes (or crashes) when exiting the lyrics sub menu so i thought about reporting it

```
value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
UnhandledException - unhandled exception: System.Collections.Generic.KeyNotFoundException: The given key 'offset' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NickvisionTagger.Shared.Controllers.MainWindowController.UpdateLyrics(LyricsInfo lyrics) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 506
   at NickvisionTagger.GNOME.Views.MainWindow.<>c__DisplayClass82_0.<Lyrics>b__0(Widget s, EventArgs ex) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 778
   at GObject.Signal`1.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.0-beta1
