### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by VampiricAlien** [NickvisionApps/Tagger#348]
Permissions are set for read and write access to everyone. Running Ubuntu 22.04. Same errors on both Snap and Flatpak
```
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, TagType tagType, ProgressManager writeProgress)
Inner Exception BEGIN
Permission denied
```
Error 2

`(NickvisionTagger.GNOME:1670913): Gtk-CRITICAL **: 14:10:26.134: Allocation height too small. Tried to allocate 99x46, but GtkBox 0x557430d3ed50 needs at least 99x47.`

Error 3

`(NickvisionTagger.GNOME:1670913): Gtk-WARNING **: 14:11:50.446: Failed to set text 'Unable to save file.mp3' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
`

**Comment by fsobolev** [comment]
Thanks for the report, could you please provide a file that caused the first error? We will try to investigate what causes the problem.

**Comment by fsobolev** [comment]
Are the files outside of home directory? Network drive, USB, or something like that? Unusual filesystem maybe?

**Comment by fsobolev** [comment]
With flatpak, could you try giving the app access to the required folder, and if it doesn't work give it full filesystem access? You can do that with [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal)
