### ISSUE TITLE
Needs a hotfix, latest flatpk update is borked

### ISSUE THREAD

**Issue by Scotty-Trees** [NickvisionApps/Tagger#438]
Hey nick! Love the app btw, the latest update from today via flathubs flatpak no longer allows the app to launch, here's the error when running it from the terminal. appreciate an update when you have the time of course.

```
scott@fedora:~$ flatpak run org.nickvision.tagger
UnhandledException - unhandled exception: System.InvalidCastException: Unable to cast object of type 'Gtk.Box' to type 'Gtk.Label'.
   at NickvisionTagger.GNOME.Views.MainWindow..ctor(Builder builder, MainWindowController controller, Application application) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 198
   at NickvisionTagger.GNOME.Views.MainWindow..ctor(MainWindowController controller, Application application) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 571
   at NickvisionTagger.GNOME.Program.OnActivate(Application sender, EventArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Program.cs:line 111
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass3_0.<ScheduleAction>b__0()
scott@fedora:~$ 
```

**Comment by nlogozzo** [comment]
Thanks for the report...let me try and fix it now.

**Comment by nlogozzo** [comment]
Just published an update with the fix!

Give it a few to come down the pipe

**Comment by Scotty-Trees** [comment]
Thanks Nick, updated and working once again, appreciate the quick update :)

**Comment by yochananmarqos** [comment]
@nlogozzo I'm seeing the same with 2024.6.0 with my AUR package:

```
❯ tagger
UnhandledException - unhandled exception: System.InvalidCastException: Unable to cast object of type 'Gtk.Box' to type 'Gtk.Label'.
   at NickvisionTagger.GNOME.Views.MainWindow..ctor(Builder builder, MainWindowController controller, Application application) in /build/tagger/src/Tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 198
   at NickvisionTagger.GNOME.Views.MainWindow..ctor(MainWindowController controller, Application application) in /build/tagger/src/Tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 571
   at NickvisionTagger.GNOME.Program.OnActivate(Application sender, EventArgs e) in /build/tagger/src/Tagger/NickvisionTagger.GNOME/Program.cs:line 111
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass3_0.<ScheduleAction>b__0()
```

**Comment by nlogozzo** [comment]
@yochananmarqos Please make sure the package pulls the repo with the `2024.6.0-1` tag and not `2024.6.0`

**Comment by yochananmarqos** [comment]
@nlogozzo Ah! That worked. :+1: 

How was anyone supposed to know that?  :thinking:

**Comment by nlogozzo** [comment]
> @nlogozzo Ah! That worked. :+1: 
> 
> How was anyone supposed to know that?  :thinking: 

I meant to mark the AUR package as out of date, mentioning the new tag...but it slipped by me...sorry 😅

**Comment by yochananmarqos** [comment]
@nlogozzo Please don't flag a package out of date that's already updated. :wink:

**Comment by nlogozzo** [comment]
@yochananmarqos Ah didn't realize you were the maintainer...thanks for being so quick :)

**Comment by yochananmarqos** [comment]
@nlogozzo No worries.
