### ISSUE TITLE
Segmentation fault with big library

### ISSUE THREAD

**Issue by RMStyle** [NickvisionApps/Tagger#73]
Opening a big music library (~35 GB) results in a crash. The application can not be started again due to a segmentation fault. 
Tested with Flathub- and AUR-Version.

**Comment by nlogozzo** [comment]
Have other editors been able to open the whole library? You might just be running out of memory with all those files. 

Try clearing the config and running the application in the terminal to see if an error message appears. (`flatpak run org.nickvision.tagger`)

**How to clear config:**
- For the flatpak version you can open the file `~/.var/app/org.nickvision.tagger/config/Nickvision/NickvisionTagger/config.json` and remove the line `"LastOpenedFolder" : "..."` 
- For the AUR version you can open the file `~/.config/Nickvision/NickvisionTagger/config.json` and remove the line `"LastOpenedFolder" : "..."` 
This way Tagger won't try to automatically open the folder.

**Comment by RMStyle** [comment]
I tried to open it with EasyTAG, it worked there.
When opening the flatpak with a cleared config, I do not get errors. As soon as I choose my music folder, I get the following errors:

```bash
TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.
TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.
TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.
TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.
TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.
TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.
TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.
```

**Comment by nlogozzo** [comment]
It could be `TagLib: String::copyFromUTF16() - Invalid UTF16 string. BOM is broken.` causing the crash. I will look into it.

**Comment by nlogozzo** [comment]
Hi, long time no see :) Tagger is now written in C# with an all new backend. Could you test this version and let me know if it fixed this issue? https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.0-beta1

**Comment by nlogozzo** [comment]
I'm marking this as closed for now...but feel-free to reopen if the beta did not solve the issue.

**Comment by RMStyle** [comment]
I finally come around to test it again. And yes it still persists, but with better logs

```
Unhandled exception. TagLib.CorruptFileException: Box header specified a size of 333319 bytes but only 4096 bytes left in the file
   at TagLib.Mpeg4.BoxHeader..ctor(File file, Int64 position)
   at TagLib.Mpeg4.FileParser..ctor(File file)
   at TagLib.Mpeg4.File.Read(ReadStyle propertiesStyle)
   at TagLib.Mpeg4.File..ctor(IFileAbstraction abstraction, ReadStyle propertiesStyle)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path, String mimetype, ReadStyle propertiesStyle)
   at TagLib.File.Create(String path)
   at NickvisionTagger.Shared.Models.MusicFile.LoadTagFromDisk() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 210
   at NickvisionTagger.Shared.Models.MusicFile..ctor(String path) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 111
   at NickvisionTagger.Shared.Models.MusicFolder.<>c__DisplayClass17_0.<ReloadMusicFilesAsync>b__0() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFolder.cs:line 58
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at NickvisionTagger.Shared.Models.MusicFolder.ReloadMusicFilesAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFolder.cs:line 52
   at NickvisionTagger.Shared.Controllers.MainWindowController.ReloadFolderAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 225
   at NickvisionTagger.Shared.Controllers.MainWindowController.OpenFolderAsync(String path) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 198
   at NickvisionTagger.Shared.Controllers.MainWindowController.StartupAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Controllers/MainWindowController.cs:line 169
   at NickvisionTagger.GNOME.Views.MainWindow.StartAsync() in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Views/MainWindow.cs:line 326
   at NickvisionTagger.GNOME.Program.OnActivate(Application sedner, EventArgs e) in /run/build/org.nickvision.tagger/NickvisionTagger.GNOME/Program.cs:line 118
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Would it be possible to get the filename?

**Comment by nlogozzo** [comment]
@RMStyle Please test https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.1-beta2
We fixed the issue where these corrupted files crash the app.
Related to #116

**Comment by RMStyle** [comment]
Yes that works, thank you! One nitpick. If the list is long the dialog gets out of bounds. Like this:
![image](https://github.com/NickvisionApps/Tagger/assets/36329720/81e69073-febf-4278-9577-23caa6de7b86)

**Comment by nlogozzo** [comment]
> Yes that works, thank you! One nitpick. If the list is long the dialog gets out of bounds. Like this:
> ![image](https://github.com/NickvisionApps/Tagger/assets/36329720/81e69073-febf-4278-9577-23caa6de7b86)
> 

Will be fixed before stable :)

@fsobolev could you fix?

**Comment by nlogozzo** [comment]
> Yes that works, thank you! One nitpick. If the list is long the dialog gets out of bounds. 

@RMStyle Fixed in https://github.com/NickvisionApps/Tagger/releases/tag/2023.7.1-beta3
